In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [23]:
df = pd.read_csv('wine_data.csv', header=None, usecols=[0,1,2,3])

In [24]:
df.columns = ['Class', 'Alcohol', 'Malic Acid', 'Ash']

In [25]:
df

Class  Alcohol  Malic Acid   Ash
0        1    14.23        1.71  2.43
1        1    13.20        1.78  2.14
2        1    13.16        2.36  2.67
3        1    14.37        1.95  2.50
4        1    13.24        2.59  2.87
..     ...      ...         ...   ...
173      3    13.71        5.65  2.45
174      3    13.40        3.91  2.48
175      3    13.27        4.28  2.26
176      3    13.17        2.59  2.37
177      3    14.13        4.10  2.74

[178 rows x 4 columns]

In [26]:
df['Class'].value_counts()

Class
2    71
1    59
3    48
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Class       178 non-null    int64  
 1   Alcohol     178 non-null    float64
 2   Malic Acid  178 non-null    float64
 3   Ash         178 non-null    float64
dtypes: float64(3), int64(1)
memory usage: 5.7 KB


# To TTS we need X and Y -- X for input cols and Y for target that model will predict

In [40]:
from sklearn.model_selection import train_test_split

x = df.drop('Class', axis=1)
# x = df.drop(df['Class']) # -- error
y = df['Class']

In [41]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.15, random_state=4) 
# random state is just a random seed so we get the same split everytime - it can be any number 

In [50]:
X_train.head()

Alcohol  Malic Acid   Ash
92     12.69        1.53  2.26
143    13.62        4.95  2.35
144    12.25        3.88  2.20
47     13.90        1.68  2.12
77     11.84        2.89  2.23

In [51]:
X_test.head()

Alcohol  Malic Acid   Ash
163    12.96        3.45  2.35
142    13.52        3.17  2.72
14     14.38        1.87  2.38
45     14.21        4.04  2.44
81     12.72        1.81  2.20

In [52]:
print(type(Y_train))
Y_train.head()

<class 'pandas.core.series.Series'>


92     2
143    3
144    3
47     1
77     2
Name: Class, dtype: int64

In [56]:
print(type(Y_test))
Y_test.head()

<class 'pandas.core.series.Series'>


163    3
142    3
14     1
45     1
81     2
Name: Class, dtype: int64

# Normalization - MinMax

In [63]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit_transform(X_train)

array([[0.43684211, 0.15612648, 0.48128342],
       [0.68157895, 0.83201581, 0.52941176],
       [0.32105263, 0.62055336, 0.44919786],
       [0.75526316, 0.18577075, 0.40641711],
       [0.21315789, 0.42490119, 0.46524064],
       [0.71578947, 0.19565217, 0.56149733],
       [0.1       , 0.        , 0.60962567],
       [0.47105263, 0.51976285, 0.5026738 ],
       [0.5       , 0.40909091, 0.71657754],
       [0.86052632, 0.23320158, 0.72727273],
       [0.68684211, 0.46640316, 0.64171123],
       [0.56052632, 0.3201581 , 0.70053476],
       [0.64473684, 0.18379447, 0.68449198],
       [0.41315789, 0.33992095, 0.44919786],
       [0.78684211, 0.18577075, 0.45454545],
       [0.65      , 0.21146245, 0.6684492 ],
       [0.42368421, 0.12252964, 0.35294118],
       [0.31315789, 0.10869565, 0.31016043],
       [0.83421053, 0.20158103, 0.5828877 ],
       [0.41315789, 0.11857708, 0.28877005],
       [0.61315789, 0.35968379, 0.52941176],
       [0.53157895, 0.25889328, 0.99465241],
       [0.

In [64]:
scaler.data_max_

array([14.83,  5.8 ,  3.23])

In [65]:
scaler.data_min_

array([11.03,  0.74,  1.36])

In [66]:
scaler.data_range_

array([3.8 , 5.06, 1.87])

In [67]:
scaler.feature_range

(0, 1)